### ISSUE TITLE
InvalidInstanceID.NotFound: The instance ID 'xxxx' does not exist status code: 400, request id:

### ISSUE THREAD

**Issue by s2000pinoy** [fairfaxmedia/flywheel#3]
I can't seem to figure out what else is missing on this. I've already configure the AWS credentials and configs correctly but I'm still getting the following error. 

**_InvalidInstanceID.NotFound: The instance ID 'xxxx' does not exist
    status code: 400, request id:_**

here's my config.json

```
_{
  "healthcheck-interval": "30s",
  "idle-timeout": "20m",
  "endpoint": "ip-172-31-29-113.ec2.internal",
  "region": "us-east-1",    
  "vhosts": {
    "ip-172-31-29-113.ec2.internal": "ec2-52-21-26-240.compute-1.amazonaws.com"
  },
  "instances": [
    "i-b477cb61"
  ],
  "autoscaling": {
    "terminate": {
      "my-safe-scaling-group": 2
    },
    "stop": [
      "my-unsafe-scaling-group"
    ]
  }
}_
```

I have verified everything from the AWS console that the hostnames and instances ID are correct but I still keep getting the error. 

Please help.

**Comment by jrosco** [comment]
@s2000pinoy the instance is definitely in region 'us-east-1'

**Comment by dgolja** [comment]
Also can you share the IAM role used with flywheel ?

**Comment by s2000pinoy** [comment]
Hi @jrosco, 

yes, they are both on the same region, same VPC, same subnet.

**Comment by s2000pinoy** [comment]
Hi @n1tr0g,
Are you talking about the credentials i used? I have a full access.

**Comment by dgolja** [comment]
Interesting ... what version of flywheel did you use ? From master branch ?

**Comment by s2000pinoy** [comment]
@n1tr0g how can i check the version? 

Is it this one? v0.9.17

**Comment by dgolja** [comment]
Hello I think I found the problem. Instead of using `region` you need to use `aws_region` and it should work. Sorry that was our mistake, because we didnt properly document it.

**Comment by s2000pinoy** [comment]
@n1tr0g, 

Which one should i change? the .json file or the .aws/config file?

**Comment by s2000pinoy** [comment]
I've edited my config file and I'm still getting the same error. 

Here's my config file

```
{
  "idle-timeout": "3h",
  "healthcheck-interval": "30s",
  "endpoint": "http://quickstep-qa.stibo.com",
  "aws_region": "us-east-1",
  "vhosts": {
    "quickstep-qa.stibo.com": "ec2-52-21-26-240.compute-1.amazonaws.com"
  },
  "instances": [
    "i-b477cb61"
  ],
  "autoscaling": {
    "terminate": {
      "my-safe-scaling-group": 2
    },
    "stop": [
      "my-unsafe-scaling-group"
    ]
  }
}
```

Here's the same error message that we are getting

```
[root@ip-172-31-21-144 flywheel]./flywheel --config alaq-config.json --listen 172.31.21.144:80
2016/08/04 14:12:50 Flywheel starting
2016/08/04 14:12:51 InvalidInstanceID.NotFound: The instance ID 'i-b477cb61' does not exist
    status code: 400, request id: 
2016/08/04 14:12:51 InvalidInstanceID.NotFound: The instance ID 'i-b477cb61' does not exist
    status code: 400, request id: 
2016/08/04 14:12:51 Healthcheck - status is now UNHEALTHY
```

**Comment by s2000pinoy** [comment]
This ticket is still open. Please re-open the ticket.

**Comment by dgolja** [comment]
can you run flywheel --version and share the output ? Also your endpoint is wrong. You should use `quickstep-qa.stibo.com` instead of `http://quickstep-qa.stibo.com`

**Comment by s2000pinoy** [comment]
Here's the message that i get when i try flywheel --version

```
[root@ip-172-31-21-144 flywheel]# ./flywheel --version
flag provided but not defined: -version
Usage of ./flywheel:
  -config string
        Config file to read settings from
  -listen string
        Address and port to listen on (default "0.0.0.0:80")
  -setuid string
        Switch to user after opening socket
  -status-file string
        File to save runtime status to
```

```
[root@ip-172-31-21-144 flywheel]# ./flywheel -version
flag provided but not defined: -version
Usage of ./flywheel:
  -config string
        Config file to read settings from
  -listen string
        Address and port to listen on (default "0.0.0.0:80")
  -setuid string
        Switch to user after opening socket
  -status-file string
        File to save runtime status to
```

**Comment by dgolja** [comment]
That mean you are not using the last flywheel version. Please update and it should work.

**Comment by s2000pinoy** [comment]
How can I update the flywheel? Do I just run through the installation again?

**Comment by dgolja** [comment]
not sure how you download it in the first place. 

You can use `go get -u github.com/fairfaxmedia/flywheel` or just pull the repository again and rebuild the binary.

**Comment by s2000pinoy** [comment]
what is the checkout version I would be using. Are we still using the same branch?

```
git checkout -b v0.9.17 v0.9.17
```

**Comment by dgolja** [comment]
use master for now or lock it to the current sha1 of master. Btw as far as i know we do not have v0.9.17

**Comment by s2000pinoy** [comment]
I'm getting the following error when I try to build flywheel. 

```
[root@ip-172-31-21-144 flywheel]# ls
alaq-config.json  cmd                  config.go       flywheel.go  healthcheck.go  http.go       LICENSE   pkg        src     version.go
aws.go            config.example.json  config_test.go  Godeps       html.go         http_test.go  Makefile  README.md  vendor
[root@ip-172-31-21-144 flywheel]# go build flywheel.go config.go healthcheck.go html.go http.go
# command-line-arguments
./flywheel.go:121: fw.Start undefined (type *Flywheel has no field or method Start)
./flywheel.go:128: fw.Stop undefined (type *Flywheel has no field or method Stop)
./flywheel.go:153: fw.Stop undefined (type *Flywheel has no field or method Stop)
```

**Comment by dgolja** [comment]
`make bin` should do the trick or `go build cmd/flywheel/main.go`

**Comment by s2000pinoy** [comment]
that did the trick. I just renamed the main to flywheel. I'm able to do the version too. 

```
[root@ip-172-31-21-144 flywheel]# ./flywheel --version
./flywheel Flywheel v0.2.0
```

**Comment by s2000pinoy** [comment]
@n1tr0g Thanks for your help.
