### ISSUE TITLE
Compilation of flywheel does not seem to be working

### ISSUE THREAD

**Issue by iambesi-zz** [fairfaxmedia/flywheel#4]
Hello,

I am quite new to GitHub and its inner workings, and thus, I imagine that I am probably just doing something dumb.  I have a number of EC2 instances in AWS and am wanting to test your flywheel tool; however, when I try to build the go code, it does not create the expected _flywheel_ binary.

A colleague of mine provided me with some old steps that he had used to compile / test your project in the past.

`export GOPATH=/root/besitest/flywheel`
`git clone https://github.com/fairfaxmedia/flywheel.git`
`go get github.com/aws/aws-sdk-go/aws` 
`go get github.com/aws/aws-sdk-go/service/autoscaling`
`go get github.com/aws/aws-sdk-go/service/ec2 go get github.com/vaughan0/go-ini`
`cd $GOPATH/src/github.com/aws/aws-sdk-go`
`git fetch`
`git checkout -b v0.9.17 v0.9.17`
`go build flywheel.go config.go healthcheck.go html.go http.go main.go`

Now, I see with you latest version you seem to have upgraded to _AWS SDK v. 1.2.4_ and have added the flywheel package to avoid using the _main_ package for everything.  For that reason, I changed the last two above steps to this instead:

`git checkout -b v1.2.4 v1.2.4`
`go build flywheel.go config.go healthcheck.go html.go http.go`

The overall build command itself worked without any errors, but sadly, no _flywheel_ binary is being built.  What am I doing wrong here?  Please let me know your thoughts.

Thanks and regards,
iambesi

**Comment by dgolja** [comment]
use the develop branch for now since it has the same functionality with some minor fixes. There is also a Makefile and you can run `make bin` and you will get the desired result.

I am planning to merge develop to master soon and release another "stable" release properly tagged.

**Comment by dgolja** [comment]
changed merged to master ... it should work now as expected.
